

import os

MYSQL_HOST = os.environ.get('MYSQL_HOST')
MYSQL_USER = os.environ.get('MYSQL_USER')
MYSQL_PASSWORD = os.environ.get('MYSQL_PASSWORD')
MYSQL_DATABASE = os.environ.get('MYSQL_DATABASE')
MYSQL_REPONSE = ''
LIENAPISMS= os.environ.get('LIENAPISMS')
LIENAPPLICATIONCLIENT=os.environ.get('LIENAPPLICATIONCLIENT')
CODECRYPTAGE=os.environ.get('CODECRYPTAGE')
"""
MYSQL_HOST = 'DESKTOP-F9PEV2V'
MYSQL_USER = 'sa'
MYSQL_PASSWORD = '123'
MYSQL_DATABASE = 'dbClinique'
MYSQL_REPONSE = ''
LIENAPISMS='http://162.19.152.91:702/'#'http://192.168.1.100:711/'
LIENAPPLICATIONCLIENT='http://162.19.152.91:702/'

CODECRYPTAGE='Y}@128eVIXfoi7'
"""